### ISSUE TITLE
[Feature request] Add example gradle project for selenide with selenoid

### ISSUE THREAD

**Issue by patsevanton** [selenide/selenide-selenoid#12]
Thanks for selenide-selenoid!
I try add selenoid to https://github.com/Drill4J/realworld-java-and-js-coverage/tree/Selenoid
Run: `./gradlew clean :build1:test -Dselenide.remote=http://localhost:4444/wd/hub`
But selenide use local browser in windows.

Please, Add example gradle project for selenide with selenoid.
Thanks!

**Comment by asolntsev** [comment]
There is a sample project: https://github.com/selenide-examples/selenoid-sample
(It uses Maven, not Gradle - but it doesn't matter for your problem).

In your project, you set `Configuration.remote` AFTER calling `open`. 
That's why method `open` (in `@BeforeAll` method) opens a local browser. `Configuration.remote` is not yet set at that moment.
