### ISSUE TITLE
Cannot update from `selenide-selenoid` 1.2.0 to 2.3.4

### ISSUE THREAD

**Issue by dmytrot-everc** [selenide/selenide-selenoid#21]
Hi, we have problem while updating to the latest selenide selenoid:
1) Imported selenide as usual in gradle ver 7.6
    `implementation group: 'org.selenide', name: 'selenide-selenoid', version: 2.3.4`

it was successfully imported, but selenide in not visible in the sope of src/main, its visible only in src/test. 
Please assist, as we dont see problems if import selenide 6.11 without selenoid. But we use selenoid features and need this lib.

**Comment by asolntsev** [comment]
Hi @dmytrot-everc.
I think `selenide.jar` is not available in `src/test` too. :)
I guess you declare `selenide` dependency with scope `testImplementation`, that's why you can use Selenide directly in `src/test`. 

Anyway, I think we should fix it in `selenide-selenoid`. Currently it declare `selenide` dependency with `implementation`, but should declare with `api`.

**Comment by asolntsev** [comment]
@dmytrot-everc selenide-selenoide 2.3.5 has been released
